# Generated by Django 5.2.11 on 2026-02-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default=225, max_length=200),
            preserve_default=False,
        ),
    ]
