# Generated by Django 5.2.11 on 2026-02-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
