# Generated by Django 5.2.11 on 2026-03-01 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_member_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='club',
            name='member_count',
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(default='GENERAL', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='organizer',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'ORGANIZER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_club', to=settings.AUTH_USER_MODEL),
        ),
    ]
